name: Build and Test with Maven

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
          ${{ runner.os }}-

    - name: Build and Test with Maven
      run: mvn clean test
      env:
        MAVEN_OPTS: "-Xmx1024m"

    - name: Display test reports (if tests fail)
      if: failure()
      run: cat target/surefire-reports/*.txt || echo "No test report found."

    - name: Upload test reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: target/surefire-reports
